package constants

var TemplateData = map[string]map[string]string{
	"python3": {
		"image":   "python:3.10.13",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.py",
		"cmd":     "python /tmp/test.py",
	},
	"rust": {
		"image":   "rust",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.rs",
		"cmd":     "rustc /tmp/test.rs -o /tmp/test\nif /tmp/test -f \"/tmp/test\"; then\n/tmp/test\nfi",
	},
	"nodejs": {
		"image":   "node",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.js",
		"cmd":     "node /tmp/test.js",
	},
	"java": {
		"image":   "khipu/openjdk17-alpine:latest",
		"memory":  "300MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "regex::class\\s+([a-zA-Z_][a-zA-Z0-9_]*)",
		"cmd":     "javac /tmp/$cap1.java -d /tmp \njava /tmp/$cap1\n",
	},
	"ruby": {
		"image":   "ruby",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.rb",
		"cmd":     "ruby /tmp/test.rb",
	},
	"golang": {
		"image":   "golang",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.go",
		"cmd":     "go run /tmp/test.go",
	},
	"cpp": {
		"image":   "gcc",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.cpp",
		"cmd":     "g++ /tmp/test.cpp -o /tmp/test\nif /tmp/test -f \"/tmp/test\"; then\n/tmp/test\nfi",
	},
	"c": {
		"image":   "gcc",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.c",
		"cmd":     "gcc /tmp/test.c -o /tmp/test\nif /tmp/test -f \"/tmp/test\"; then\n/tmp/test.c\nfi",
	},
	"shell": {
		"image":   "gcc",
		"memory":  "100MB",
		"cpuset":  "0-3",
		"timeout": "30",
		"file":    "/tmp/test.sh",
		"cmd":     "chmod +x /tmp/test.sh\n/tmp/test.sh",
	},
}
